### ISSUE TITLE
Can't do pydantic serialization

### ISSUE THREAD

**Issue by margaretlange** [tortoise/tortoise-orm#1925]
**Describe the bug**

My initial bug was in my own code, but I can recreate the problem running the example code here:
https://tortoise.github.io/examples/pydantic.html

**To Reproduce**

```
from tortoise import Tortoise, fields, run_async
from tortoise.contrib.pydantic import pydantic_model_creator, pydantic_queryset_creator
from tortoise.models import Model


class Tournament(Model):
    id = fields.IntField(primary_key=True)
    name = fields.TextField()
    created_at = fields.DatetimeField(auto_now_add=True)

    events: fields.ReverseRelation["Event"]

    class Meta:
        ordering = ["name"]


class Event(Model):
    id = fields.IntField(primary_key=True)
    name = fields.TextField()
    created_at = fields.DatetimeField(auto_now_add=True)
    tournament: fields.ForeignKeyNullableRelation[Tournament] = fields.ForeignKeyField(
        "models.Tournament", related_name="events", null=True
    )
    participants: fields.ManyToManyRelation["Team"] = fields.ManyToManyField(
        "models.Team", related_name="events", through="event_team"
    )
    address: fields.OneToOneNullableRelation["Address"]

    class Meta:
        ordering = ["name"]


class Address(Model):
    city = fields.CharField(max_length=64)
    street = fields.CharField(max_length=128)
    created_at = fields.DatetimeField(auto_now_add=True)

    event: fields.OneToOneRelation[Event] = fields.OneToOneField(
        "models.Event", on_delete=fields.OnDelete.CASCADE, related_name="address", primary_key=True
    )

    class Meta:
        ordering = ["city"]


class Team(Model):
    id = fields.IntField(primary_key=True)
    name = fields.TextField()
    created_at = fields.DatetimeField(auto_now_add=True)

    events: fields.ManyToManyRelation[Event]

    class Meta:
        ordering = ["name"]


async def run():
    await Tortoise.init(db_url="sqlite://:memory:", modules={"models": ["__main__"]})
    await Tortoise.generate_schemas()
    Event_Pydantic = pydantic_model_creator(Event)
    Event_Pydantic_List = pydantic_queryset_creator(Event)
    Tournament_Pydantic = pydantic_model_creator(Tournament)
    Team_Pydantic = pydantic_model_creator(Team)

    # print(Event_Pydantic_List.schema_json(indent=4))
    # print(Event_Pydantic.schema_json(indent=4))
    # print(Tournament_Pydantic.schema_json(indent=4))
    # print(Team_Pydantic.schema_json(indent=4))

    tournament = await Tournament.create(name="New Tournament")
    tournament2 = await Tournament.create(name="Old Tournament")
    await Event.create(name="Empty")
    event = await Event.create(name="Test", tournament=tournament)
    event2 = await Event.create(name="TestLast", tournament=tournament)
    event3 = await Event.create(name="Test2", tournament=tournament2)
    await Address.create(city="Santa Monica", street="Ocean", event=event)
    await Address.create(city="Somewhere Else", street="Lane", event=event2)
    team1 = await Team.create(name="Onesies")
    team2 = await Team.create(name="T-Shirts")
    team3 = await Team.create(name="Alternates")
    await event.participants.add(team1, team2, team3)
    await event2.participants.add(team1, team2)
    await event3.participants.add(team1, team3)

    p = await Event_Pydantic.from_tortoise_orm(await Event.get(name="Test"))
    print("One Event:", p.model_dump_json(indent=4))

    p = await Tournament_Pydantic.from_tortoise_orm(await Tournament.get(name="New Tournament"))
    print("One Tournament:", p.model_dump_json(indent=4))

    p = await Team_Pydantic.from_tortoise_orm(await Team.get(name="Onesies"))
    print("One Team:", p.model_dump_json(indent=4))

    pl = await Event_Pydantic_List.from_queryset(Event.filter(address__event_id__isnull=True))
    print("All Events without addresses:", pl.model_dump_json(indent=4))


if __name__ == "__main__":
    run_async(run())
```
I get the following stack trace

> Traceback (most recent call last):
  File "/home/maggie/test_tortoise/example_four.py", line 103, in <module>
    run_async(run())
  File "/home/maggie/test_tortoise/venv/lib/python3.10/site-packages/tortoise/__init__.py", line 643, in run_async
    loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/maggie/test_tortoise/example_four.py", line 64, in run
    Event_Pydantic = pydantic_model_creator(Event)
  File "/home/maggie/test_tortoise/venv/lib/python3.10/site-packages/tortoise/contrib/pydantic/creator.py", line 633, in pydantic_model_creator
    return pmc.create_pydantic_model()
  File "/home/maggie/test_tortoise/venv/lib/python3.10/site-packages/tortoise/contrib/pydantic/creator.py", line 375, in create_pydantic_model
    self._process_field(field_name, field)
  File "/home/maggie/test_tortoise/venv/lib/python3.10/site-packages/tortoise/contrib/pydantic/creator.py", line 415, in _process_field
    field_property, is_to_one_relation = self._process_normal_field(
  File "/home/maggie/test_tortoise/venv/lib/python3.10/site-packages/tortoise/contrib/pydantic/creator.py", line 457, in _process_normal_field
    return self._process_single_field_relation(field_name, field, json_schema_extra), True
  File "/home/maggie/test_tortoise/venv/lib/python3.10/site-packages/tortoise/contrib/pydantic/creator.py", line 471, in _process_single_field_relation
    model: type[PydanticModel] | None = self._get_submodel(python_type, field_name)
  File "/home/maggie/test_tortoise/venv/lib/python3.10/site-packages/tortoise/contrib/pydantic/creator.py", line 552, in _get_submodel
    pmodel = _pydantic_recursion_protector(
  File "/home/maggie/test_tortoise/venv/lib/python3.10/site-packages/tortoise/contrib/pydantic/creator.py", line 100, in _pydantic_recursion_protector
    return pmc.create_pydantic_model()
  File "/home/maggie/test_tortoise/venv/lib/python3.10/site-packages/tortoise/contrib/pydantic/creator.py", line 388, in create_pydantic_model
    model = create_model(
  File "/home/maggie/test_tortoise/venv/lib/python3.10/site-packages/pydantic/main.py", line 1762, in create_model
    return meta(
  File "/home/maggie/test_tortoise/venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 110, in __new__
    config_wrapper = ConfigWrapper.for_model(bases, namespace, kwargs)
  File "/home/maggie/test_tortoise/venv/lib/python3.10/site-packages/pydantic/_internal/_config.py", line 128, in for_model
    raise PydanticUserError(
pydantic.errors.PydanticUserError: `model_config` cannot be used as a model field name. Use `model_config` for model configuration.

For further information visit https://errors.pydantic.dev/2.11/u/model-config-invalid-field-name

**Expected behavior**
I expected the code to run without error.

**Additional context**
I am running on ubuntu 22.04.
Results of running pip freeze:

> aiosqlite==0.21.0
annotated-types==0.7.0
cfgv==3.4.0
distlib==0.3.9
filelock==3.18.0
identify==2.6.9
iso8601==2.1.0
nodeenv==1.9.1
platformdirs==4.3.7
pre_commit==4.2.0
pydantic==2.11.1
pydantic_core==2.33.0
pypika-tortoise==0.5.0
pytz==2025.2
PyYAML==6.0.2
tortoise-orm==0.24.2
typing-inspection==0.4.0
typing_extensions==4.13.0
virtualenv==20.29.3

I wasn't getting this error until a couple days ago, fwiw. My code hasn't changed significantly. My requirements.txt files don't show all the packages installed, so I'm wondering if somehow my environment changed.

**Comment by margaretlange** [comment]
Update: I ran the pydantic serialization test suite for this repository successfully and used that environment to discover that you need to revert to pydantic 2.10.6 and pydantic-core 2.27.2 to make this error go away.  I think that I was installing pydantic via fastapi and that process updated pydantic a couple days ago. 
I don't know if this incompatibility is known and tolerated but if not someone might want to look into it.

**Comment by margaretlange** [comment]
I can look into this a bit.

**Comment by arnaudblois** [comment]
I've faced the same issue and took a deeper look. Pydantic 2.11, released yesterday, is now enforcing strict validation against having `model_config` as a field, which is what `pydantic_model_creator` ultimately does under the hood.

The offending line is [this one](https://github.com/tortoise/tortoise-orm/blob/0.24.2/tortoise/contrib/pydantic/creator.py#L387). The error can be fixed by removing this line and adding `model.model_config= self._pconfig` a few lines down.

Happy to PR if it helps

**Comment by margaretlange** [comment]
Yes, go ahead and PR if the fix is that simple! I'm still new to pydantic.
(Hopefully the poetry dependencies for the tests will be updated automatically to the latest pydantic so they will run against that?)

**Comment by C5H12O5** [comment]
Not passing the `model_config` parameter does not resolve all issues. Due to changes in the `create_model` method in Pydantic version 2.11, using `computed fields` in the `PydanticMeta` class can also cause errors. My solution is to dynamically create a base class that includes both `model_config` and `computed fields`, and pass it to the `create_model` method.

```python
from pydantic import create_model
from pydantic.fields import ComputedFieldInfo
from tortoise.contrib.pydantic.base import PydanticModel
from tortoise.contrib.pydantic.creator import (
    _MODEL_INDEX,
    PydanticModelCreator,
    _cleandoc,
)


def patched_create_pydantic_model(self) -> type[PydanticModel]:
    for field_name, field in self._field_map.items():
        self._process_field(field_name, field)

    self._name, self._title = self.get_name()

    if self._hash in _MODEL_INDEX:
        # there is a model exactly the same, but the name could be different
        hashed_model = _MODEL_INDEX[self._hash]
        if hashed_model.__name__ == self._name:
            # also the same name
            return _MODEL_INDEX[self._hash]

    self._pconfig = self._initialize_pconfig()

    common_fields = {}
    computed_fields = {}
    for k, v in self._properties.items():
        if isinstance(getattr(v, "decorator_info", None), ComputedFieldInfo):
            computed_fields[k] = v
        else:
            common_fields[k] = v
    base_model = type(
        "BasePydanticModel",
        (PydanticModel,),
        {"model_config": self._pconfig, **computed_fields},
    )
    model = create_model(
        self._name,
        __base__=base_model,
        __module__=self._module,
        __validators__=self._validators,
        **common_fields,
    )
    # Copy the Model docstring over
    model.__doc__ = _cleandoc(self._cls)
    # Store the base class
    model.model_config["orig_model"] = self._cls  # type: ignore
    # Store model reference so we can de-dup it later on if needed.
    _MODEL_INDEX[self._hash] = model
    return model


PydanticModelCreator.create_pydantic_model = patched_create_pydantic_model
```

**Comment by margaretlange** [comment]
> Due to changes in the `create_model` method in Pydantic version 2.11, using computed fields in the `PydanticMeta` class can also cause errors.

Can you give an example of this for tortoise so I can understand it better?

> My solution is to dynamically create a base class that includes both `model_config` and computed fields, and pass it to the `create_model` method.

If we are going to this trouble, why not just take it a step further and dynamically create the full model class inherited from BasePydanticModel? Under Pydantic version 2.11, how much is `create_model` doing for the tortoise code base here?

**Comment by C5H12O5** [comment]
@margaretlange 

The `tortoise-orm` converts ORM Models to Pydantic Models by calling the [create_model](https://docs.pydantic.dev/2.11/concepts/models/#dynamic-model-creation) method. If `computed fields` are used in the `PydanticMeta` class, `tortoise-orm` passes the return value of the  [@computed_field](https://docs.pydantic.dev/2.11/concepts/fields/#the-computed_field-decorator) decorator to the `field_definitions` parameter of the `create_model` method. This approach worked in versions of Pydantic prior to 2.11. However, starting from version 2.11, Pydantic treats all fields in `field_definitions` as common fields, which causes an error. Equivalent code examples are as follows:

- **Non-dynamic creation**

```python
from pydantic import BaseModel, computed_field

class Square(BaseModel):
    length: float

    @computed_field
    def area(self) -> float:
        return self.length**2

print(Square(length=2).model_dump())
# Output: {'length': 2.0, 'area': 4.0}
```

- **Dynamic creation**

```python
from pydantic import BaseModel, computed_field, create_model

def area(self) -> float:
    return self.length**2

Square = create_model(
    "Square",
    __base__=BaseModel,
    length=(float, "length"),
    area=computed_field(area),
)

print(Square(length=2).model_dump())
# For pydantic < 2.11, Output: {'length': 2.0, 'area': 4.0}
# For pydantic >= 2.11, raises AttributeError: 'property' object has no attribute '__mro__'
```

I am not sure if this is an issue that Pydantic needs to handle, as its official documentation does not mention how to use `computed_field` when dynamically creating models. Therefore, I temporarily resolved this issue using the patch code I mentioned in my previous comment.

**Comment by henadzit** [comment]
@margaretlange @C5H12O5 @arnaudblois thanks for looking into this! Is there a path forward to resolve this? Should we create  an issue or start a discussion in Pydantic?

**Comment by margaretlange** [comment]
I don't know if it's worth talking to folks over at pydantic as presumably they removed certain capabilities from create_model deliberately. what do you think? Maybe we should just test @C5H12O5's patch against existing tests (if they haven't already) and they can do a PR.
p.s.  I can do the PR but I don't want to steal @C5H12O5's thunder! let me know

**Comment by C5H12O5** [comment]
@henadzit @margaretlange Oh, I didn't run the tests before. I was just trying to make my project error-free. I can submit a PR if the fix passes all tests across multiple versions of pydantic. Additionally, I will open an issue in the pydantic repository. If this issue is indeed a bug, it might be fixed in future versions.

**Comment by henadzit** [comment]
Just released the fix in 0.25.0.
